/* ═══════════════════════════════════════════════════════════════════
   STAGE MARKUP
   The persistent visual layer shared by every scene:
     • #ui          — fixed title / VAT counters / corner labels
     • #liquid-bg   — draining liquid background (Scenes 1–2)
     • #main-svg    — the SVG canvas where all shape animation happens
   Per-scene scroll sections (#scroller) and text overlays (.stext) are
   NOT here — the engine injects those from each scene module.
═══════════════════════════════════════════════════════════════════ */

export const stageMarkup = /* html */ `
  <!-- FIXED UI LAYER — overlaid, pointer-events:none by default -->
  <div id="ui">
    <span id="lbl-good-news">GOOD&nbsp;&nbsp;NEWS</span>
    <span id="lbl-year">1973</span>
    <div id="euro-counter">€&nbsp;<span id="euro-num">0</span></div>

    <div id="scene-title">
      <div class="t-tracked">ÖSTERREICH</div>
      <div class="t-serif"> UND DAS ENDE DER</div>
      <div class="t-italic">TAMPONSTEUER</div>
    </div>

    <!-- The big VAT number drains 20→0%, shrinks down, then "MwST." fades in.
         "0%" (the core) stays centered under the spine; "MwST." is absolutely
         positioned to its right (smaller), so it never shifts the number. -->
    <div id="vat-big"><span id="vat-big-core"><span id="vat-big-num">20</span>%<span id="vat-big-tax">MwST.</span></span></div>

    <!-- Scroll hint — fades in once the intro build-up settles, fades out
         again on the first scroll (driven by countdown.js). -->
    <div id="scroll-hint" aria-hidden="true">
      <span class="sh-label">SCROLLEN</span>
      <svg class="sh-arrow" viewBox="0 0 24 24" width="22" height="22" fill="none"
           stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <path d="M12 4 V19 M5 12.5 L12 19.5 L19 12.5"/>
      </svg>
    </div>

    <!-- Info icon — appears top-right of the big circle when hover is active
         (driven by pie-26.js). Tooltip mirrors the scroll-hint style. -->
    <div id="info-hint" aria-hidden="true">
      <div id="info-icon-btn">
        <span class="info-i">i</span>
      </div>
      <span id="info-label">HOVER</span>
    </div>
  </div>

  <!-- LIQUID BACKGROUND (Scenes 1–2) — drains as VAT counts 20→0 -->
  <div id="liquid-bg">
    <svg id="liquid-svg" viewBox="0 0 1000 80" preserveAspectRatio="none"
         xmlns="http://www.w3.org/2000/svg">
      <path id="liquid-wave-path" fill="#D63335"
            d="M 0,15 C 167,8 333,22 500,15 C 667,8 833,22 1000,15 L 1000,80 L 0,80 Z"/>
    </svg>
  </div>

  <!-- FIXED SVG CANVAS -->
  <svg id="main-svg" viewBox="0 0 1000 562" preserveAspectRatio="xMidYMid meet"
       xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
    <defs>
      <filter id="blob-filter" x="-40%" y="-40%" width="180%" height="180%"
              color-interpolation-filters="linearRGB">
        <feTurbulence id="fe-turb" type="turbulence" baseFrequency="0.035"
                      numOctaves="3" seed="2" result="noise"/>
        <feDisplacementMap id="fe-disp" in="SourceGraphic" in2="noise" scale="0"
                           xChannelSelector="R" yChannelSelector="G"/>
      </filter>
      <clipPath id="circle-fill-clip">
        <circle cx="775" cy="281" r="90"/>
      </clipPath>

      <!-- Gooey / metaball filter — used while the big circle splits into the
           12 month circles (Scene 8). Blur + a high-contrast alpha matrix make
           overlapping circles merge into one liquid mass with stretchy necks.
           #gooey-blur's stdDeviation is animated to 0 over the last third of the
           split so the 12 circles end up perfectly round, sharp and precise. -->
      <filter id="gooey" filterUnits="userSpaceOnUse" x="600" y="0" width="350" height="562"
              color-interpolation-filters="sRGB">
        <feGaussianBlur id="gooey-blur" in="SourceGraphic" stdDeviation="0" result="blur"/>
        <feColorMatrix in="blur" type="matrix"
                       values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 19 -9"/>
      </filter>
    </defs>

    <!-- Center vertical axis (draws in Scene 3) -->
    <line id="c-axis" x1="500" y1="42" x2="500" y2="510" stroke="#C9C9C0"
          stroke-width="2" stroke-dasharray="468" stroke-dashoffset="468" opacity="0"/>

    <text id="lbl-periode" x="500" y="11" text-anchor="middle" class="svg-mono"
          font-size="9" fill="#1a1a1a" letter-spacing="2" opacity="0">DIE PERIODE</text>
    <text id="lbl-xxxx" x="985" y="11" text-anchor="end" class="svg-mono svg-italic"
          font-size="9" fill="#1a1a1a" letter-spacing="1" opacity="0">XXXX</text>

    <!-- Period dots on center axis (generated by buildStage) -->
    <g id="period-dots" opacity="0"></g>

    <!-- Circle — hairline grey outline -->
    <circle id="c-outline" cx="775" cy="281" r="90" fill="none" stroke="#D0D0C7"
            stroke-width="0.8" opacity="0"/>

    <!-- Liquid stream + fill (Scene 4) -->
    <rect id="liq-stream" x="772" y="50" width="6" height="0" fill="#D63335" opacity="0"/>
    <rect id="liq-fill" x="685" y="371" width="180" height="0" fill="#D63335"
          clip-path="url(#circle-fill-clip)" opacity="0"/>

    <!-- Spinner circle — stroke draws around outline -->
    <circle id="c-spinner" cx="775" cy="281" r="90" fill="none" stroke="#D63335"
            stroke-width="1.8" stroke-linecap="round" stroke-dasharray="565.5"
            stroke-dashoffset="565.5" transform="rotate(-90 775 281)" opacity="0"/>

    <!-- Filled circle — solid red -->
    <circle id="c-fill" cx="775" cy="281" r="90" fill="#D63335" opacity="0"/>

    <!-- Pie chart arcs (paths generated by buildStage) -->
    <path id="pie-bg" fill="#D63335" opacity="0"/>
    <path id="pie-hl" fill="#F4DEDB" opacity="0"/>

    <!-- Pie chart text labels -->
    <g id="pie-txt" opacity="0">
      <text x="775" y="262" text-anchor="middle" class="svg-mono" font-size="7.5" fill="#1a1a1a" letter-spacing="1.5">DAS SIND</text>
      <text x="775" y="279" text-anchor="middle" class="svg-serif svg-italic" font-size="19" fill="#1a1a1a">26%</text>
      <text x="775" y="292" text-anchor="middle" class="svg-mono" font-size="7.5" fill="#1a1a1a" letter-spacing="1.5">DER WELTBEVÖLKERUNG</text>
    </g>

    <!-- 12 month circles (generated by buildStage) — gooey filter lets them
         emerge as one liquid mass that splits apart (Scene 8). -->
    <g id="m-circles" opacity="0" filter="url(#gooey)"></g>

    <!-- Main thin rectangle (Scene 10 → 11) -->
    <rect id="m-rect" x="720" y="70" width="10" height="422" fill="#D63335" opacity="0"/>

    <!-- Bottom 31-year de-emphasis overlay (fades in during Phase 5 of Die Periode) -->
    <!-- Covers y=148→492: the lower 31 of 38 years, tracking mRect's x/width -->
    <rect id="r-rect" x="720" y="148" width="10" height="344" fill="#F4DEDB" opacity="0"/>

    <!-- 456 horizontal lines (generated by buildStage) -->
    <g id="lines" opacity="0"></g>

    <!-- 38 year-divider lines within the rect bounds (generated by buildStage) -->
    <g id="lines-38" opacity="0"></g>

    <!-- ── SPINE SCROLL INDICATOR ──────────────────────────────────────
         The central axis doubles as the page scrollbar: a red fill grows
         down the spine and the period dots fill in as it passes them, both
         tracking overall scroll progress. An invisible hit-area lets you
         click / drag the spine to seek. Driven by core/spine.js; the native
         scrollbar is hidden in base.css. -->
    <line id="c-axis-progress" x1="500" y1="42" x2="500" y2="42"
          stroke="#A9A99F" stroke-width="5" stroke-linecap="round" opacity="0"/>
    <rect id="spine-hit" x="486" y="42" width="28" height="468" fill="transparent"/>
  </svg>

  <!-- Scroll spacer sections injected here by the engine -->
  <div id="scroller"></div>

  <!-- Scene text overlays injected here by the engine -->
  <div id="overlays"></div>
`;
