/* ═══════════════════════════════════════════════════════════════════
   STAGE MARKUP
   The persistent visual layer shared by every scene:
     • #ui          — fixed title / VAT counters / corner labels
     • #liquid-bg   — draining liquid background (Scenes 1–2)
     • #main-svg    — the SVG canvas where all shape animation happens
   Per-scene scroll sections (#scroller) and text overlays (.stext) are
   NOT here — the engine injects those from each scene module.
═══════════════════════════════════════════════════════════════════ */

export const stageMarkup = /* html */ `
  <!-- FIXED UI LAYER — overlaid, pointer-events:none by default -->
  <div id="ui">
    <span id="lbl-good-news">GOOD&nbsp;&nbsp;NEWS</span>
    <span id="lbl-year">1973</span>
    <div id="euro-counter">€&nbsp;<span id="euro-num">0</span></div>

    <div id="scene-title">
      <div class="t-tracked">ÖSTERREICH</div>
      <div class="t-serif"> UND DAS ENDE DER</div>
      <div class="t-italic">TAMPONSTEUER</div>
    </div>

    <!-- The big VAT number drains 20→0%, shrinks down, then "MwST." fades in.
         "0%" (the core) stays centered under the spine; "MwST." is absolutely
         positioned to its right (smaller), so it never shifts the number. -->
    <div id="vat-big"><span id="vat-big-core"><span id="vat-big-num">20</span>%<span id="vat-big-tax">MwST.</span></span></div>

    <!-- Scroll hint — fades in once the intro build-up settles, fades out
         again on the first scroll (driven by countdown.js). -->
    <div id="scroll-hint" aria-hidden="true">
      <span class="sh-label">SCROLLEN</span>
      <svg class="sh-arrow" viewBox="0 0 24 24" width="22" height="22" fill="none"
           stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <path d="M12 4 V19 M5 12.5 L12 19.5 L19 12.5"/>
      </svg>
    </div>

    <!-- Info icon — appears top-right of the big circle when hover is active
         (driven by pie-26.js). Tooltip mirrors the scroll-hint style. -->
    <div id="info-hint" aria-hidden="true">
      <div id="info-icon-btn">
        <span class="info-i">i</span>
      </div>
      <span id="info-label">HOVER</span>
    </div>
  </div>

  <!-- LIQUID BACKGROUND (Scenes 1–2) — drains as VAT counts 20→0 -->
  <div id="liquid-bg">
    <svg id="liquid-svg" viewBox="0 0 1000 80" preserveAspectRatio="none"
         xmlns="http://www.w3.org/2000/svg">
      <path id="liquid-wave-path" fill="#D63335"
            d="M 0,15 C 167,8 333,22 500,15 C 667,8 833,22 1000,15 L 1000,80 L 0,80 Z"/>
    </svg>
  </div>

  <!-- FIXED SVG CANVAS -->
  <svg id="main-svg" viewBox="0 0 1000 562" preserveAspectRatio="xMidYMid meet"
       xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
    <defs>
      <filter id="blob-filter" x="-40%" y="-40%" width="180%" height="180%"
              color-interpolation-filters="linearRGB">
        <feTurbulence id="fe-turb" type="turbulence" baseFrequency="0.035"
                      numOctaves="3" seed="2" result="noise"/>
        <feDisplacementMap id="fe-disp" in="SourceGraphic" in2="noise" scale="0"
                           xChannelSelector="R" yChannelSelector="G"/>
      </filter>
      <clipPath id="circle-fill-clip">
        <circle cx="775" cy="281" r="90"/>
      </clipPath>

      <!-- Gooey / metaball filter — used while the big circle splits into the
           12 month circles (Scene 8). Blur + a high-contrast alpha matrix make
           overlapping circles merge into one liquid mass with stretchy necks.
           #gooey-blur's stdDeviation is animated to 0 over the last third of the
           split so the 12 circles end up perfectly round, sharp and precise. -->
      <filter id="gooey" filterUnits="userSpaceOnUse" x="530" y="-50" width="480" height="662"
              color-interpolation-filters="sRGB">
        <feGaussianBlur id="gooey-blur" in="SourceGraphic" stdDeviation="0" result="blur"/>
        <feColorMatrix in="blur" type="matrix"
                       values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 19 -9"/>
      </filter>
    </defs>

    <!-- Center vertical axis (draws in Scene 3) -->
    <line id="c-axis" x1="500" y1="42" x2="500" y2="510" stroke="#C9C9C0"
          stroke-width="2" stroke-dasharray="468" stroke-dashoffset="468" opacity="0"/>

    <text id="lbl-periode" x="500" y="11" text-anchor="middle" class="svg-mono"
          font-size="9" fill="#1a1a1a" letter-spacing="2" opacity="0">DIE PERIODE</text>
    <text id="lbl-xxxx" x="985" y="11" text-anchor="end" class="svg-mono svg-italic"
          font-size="9" fill="#1a1a1a" letter-spacing="1" opacity="0">XXXX</text>

    <!-- Period dots on center axis (generated by buildStage) -->
    <g id="period-dots" opacity="0"></g>

    <!-- Circle — hairline grey outline; fills itself red once the spinner draws -->
    <circle id="c-outline" cx="775" cy="281" r="90" fill="#D63335" fill-opacity="0"
            stroke="#D0D0C7" stroke-width="0.8" opacity="0" pointer-events="all"/>

    <!-- Liquid stream + fill (Scene 4) -->
    <rect id="liq-stream" x="772" y="50" width="6" height="0" fill="#D63335" opacity="0"/>
    <rect id="liq-fill" x="685" y="371" width="180" height="0" fill="#D63335"
          clip-path="url(#circle-fill-clip)" opacity="0"/>

    <!-- Spinner circle — stroke draws around outline -->
    <circle id="c-spinner" cx="775" cy="281" r="90" fill="none" stroke="#D63335"
            stroke-width="1.8" stroke-linecap="round" stroke-dasharray="565.5"
            stroke-dashoffset="565.5" transform="rotate(-90 775 281)" opacity="0"/>

    <!-- Pie chart arcs (paths generated by buildStage) -->
    <path id="pie-bg" fill="#D63335" opacity="0"/>
    <path id="pie-hl" fill="#F4DEDB" opacity="0"/>

    <!-- Pie chart text labels -->
    <g id="pie-txt" opacity="0">
      <text x="775" y="262" text-anchor="middle" class="svg-mono" font-size="7.5" fill="#1a1a1a" letter-spacing="1.5">DAS SIND</text>
      <text x="775" y="279" text-anchor="middle" class="svg-serif svg-italic" font-size="19" fill="#1a1a1a">26%</text>
      <text x="775" y="292" text-anchor="middle" class="svg-mono" font-size="7.5" fill="#1a1a1a" letter-spacing="1.5">DER WELTBEVÖLKERUNG</text>
    </g>

    <!-- 12 month circles (generated by buildStage) — gooey filter lets them
         emerge as one liquid mass that splits apart (Scene 8). -->
    <g id="m-circles" opacity="0" filter="url(#gooey)"></g>

    <!-- Main thin rectangle (Scene 10 → 11) — centered at CX=775 -->
    <rect id="m-rect" x="770" y="70" width="10" height="422" fill="#D63335" opacity="0"/>

    <!-- Top 31-year de-emphasis overlay (wipes in top→bottom during scene C) -->
    <!-- Covers y=70→414: the upper 31 of 38 years; bottom 7 stay solid red -->
    <rect id="r-rect" x="770" y="70" width="10" height="344" fill="#F4DEDB" opacity="0"/>

    <!-- 456 horizontal lines (generated by buildStage) -->
    <g id="lines" opacity="0"></g>

    <!-- 38 year-divider lines within the rect bounds (generated by buildStage) -->
    <g id="lines-38" opacity="0"></g>

    <!-- ── CHAPTER 5: 3D TAMPON (realistic shaded illustration, interactive 3D rotation) -->
    <g id="tampon-3d" opacity="0" style="cursor:crosshair; transform-box:fill-box; transform-origin:50% 50%;">
      <defs>
        <!-- Horizontal gradient: left highlight → right shadow (cylinder shading) -->
        <linearGradient id="t-body" x1="0" y1="0" x2="1" y2="0" gradientUnits="objectBoundingBox">
          <stop offset="0%"   stop-color="#ffffff"/>
          <stop offset="10%"  stop-color="#FDFAF6"/>
          <stop offset="38%"  stop-color="#F4EEE4"/>
          <stop offset="68%"  stop-color="#DDD4C2"/>
          <stop offset="100%" stop-color="#C2B49E"/>
        </linearGradient>
        <!-- Vertical gradient: subtle darkening toward bottom -->
        <linearGradient id="t-vdepth" x1="0" y1="0" x2="0" y2="1" gradientUnits="objectBoundingBox">
          <stop offset="0%"   stop-color="rgba(255,255,255,0.07)"/>
          <stop offset="55%"  stop-color="rgba(0,0,0,0)"/>
          <stop offset="100%" stop-color="rgba(0,0,0,0.13)"/>
        </linearGradient>
        <!-- Top dome: radial gradient for spherical highlight -->
        <radialGradient id="t-dome" cx="36%" cy="32%" r="64%" gradientUnits="objectBoundingBox">
          <stop offset="0%"   stop-color="#ffffff"/>
          <stop offset="42%"  stop-color="#F5F0E6"/>
          <stop offset="100%" stop-color="#CCC4B0"/>
        </radialGradient>
        <!-- Bottom face (darker, in shadow) -->
        <radialGradient id="t-bot" cx="44%" cy="44%" r="58%" gradientUnits="objectBoundingBox">
          <stop offset="0%"   stop-color="#C8BEA8"/>
          <stop offset="100%" stop-color="#9E9280"/>
        </radialGradient>
      </defs>

      <!-- Drop shadow under tampon -->
      <ellipse cx="790" cy="374" rx="62" ry="9" fill="rgba(0,0,0,0.09)"/>

      <!-- BODY: tapered trapezoid (wider at bottom) filled with horizontal gradient -->
      <path d="M 738,178 L 725,356 A 65,20 0 0 0 855,356 L 842,178 Z" fill="url(#t-body)"/>
      <!-- Vertical depth overlay on body -->
      <path d="M 738,178 L 725,356 A 65,20 0 0 0 855,356 L 842,178 Z" fill="url(#t-vdepth)"/>

      <!-- Cotton ribs (horizontal bands across body, tapered with body width) -->
      <ellipse cx="790" cy="205" rx="50" ry="6.5" fill="none" stroke="#CAC0B0" stroke-width="1.3"/>
      <ellipse cx="790" cy="228" rx="52" ry="7"   fill="none" stroke="#CAC0B0" stroke-width="1.3"/>
      <ellipse cx="790" cy="251" rx="54" ry="7.5" fill="none" stroke="#CAC0B0" stroke-width="1.3"/>
      <ellipse cx="790" cy="275" rx="56" ry="8"   fill="none" stroke="#CAC0B0" stroke-width="1.3"/>
      <ellipse cx="790" cy="299" rx="57" ry="8.5" fill="none" stroke="#CAC0B0" stroke-width="1.3"/>
      <ellipse cx="790" cy="323" rx="59" ry="9"   fill="none" stroke="#CAC0B0" stroke-width="1.3"/>
      <ellipse cx="790" cy="347" rx="62" ry="9.5" fill="none" stroke="#CAC0B0" stroke-width="1.3"/>

      <!-- TOP DOME: rounded spherical cap with highlight -->
      <ellipse cx="790" cy="178" rx="52" ry="16" fill="url(#t-dome)"/>
      <!-- Dome edge line for definition -->
      <ellipse cx="790" cy="178" rx="52" ry="16" fill="none" stroke="#C8BEB0" stroke-width="0.7"/>

      <!-- Left-side specular highlight (bright streak = cylinder light reflection) -->
      <path d="M 750,186 C 747,220 744,268 746,326"
            stroke="rgba(255,255,255,0.55)" stroke-width="5" fill="none" stroke-linecap="round"/>

      <!-- BOTTOM ELLIPSE FACE (visible, darker = facing away from light) -->
      <ellipse cx="790" cy="356" rx="65" ry="20" fill="url(#t-bot)"/>
      <ellipse cx="790" cy="356" rx="65" ry="20" fill="none" stroke="#9E9280" stroke-width="0.7"/>

      <!-- STRING: wavy line hanging below -->
      <path d="M 790,376 C 794,392 789,410 793,426 C 796,438 788,447 790,454 C 792,461 785,463 786,458"
            stroke="#AEA090" stroke-width="2.8" fill="none" stroke-linecap="round"/>

      <!-- 17.000 text, centered in the tampon body -->
      <text x="790" y="270" text-anchor="middle" dominant-baseline="middle"
            class="svg-serif" font-size="22" fill="#3a3028" letter-spacing="3" opacity="0.8">17.000</text>
    </g>

    <!-- ── CHAPTER 5: 25 EURO COINS (generated by buildStage) -->
    <g id="coins-grp" opacity="0"></g>

    <!-- ── CHAPTER 6: POVERTY CIRCLE (large, 1.4M people) -->
    <circle id="pov-circle" cx="790" cy="281" r="0" fill="#D63335" opacity="0"/>

    <!-- 17% hover pie sector over big circle -->
    <path id="pov-pie-17" fill="#F4DEDB" opacity="0"/>

    <!-- 500k sub-circle inside poverty circle (darker) -->
    <circle id="pov-sub" cx="790" cy="281" r="0" fill="#531416" opacity="0"/>

    <!-- Cumulative pie sectors on pov-sub (added one at a time) -->
    <path id="pov-pie-90" fill="#D63335" opacity="0"/>
    <path id="pov-pie-60" fill="#F07E7D" opacity="0"/>
    <path id="pov-pie-15" fill="#F4DEDB" opacity="0"/>
    <path id="pov-pie-12" fill="#C9C9C0" opacity="0"/>

    <!-- ── SPINE SCROLL INDICATOR ──────────────────────────────────────
         The central axis doubles as the page scrollbar: a red fill grows
         down the spine and the period dots fill in as it passes them, both
         tracking overall scroll progress. An invisible hit-area lets you
         click / drag the spine to seek. Driven by core/spine.js; the native
         scrollbar is hidden in base.css. -->
    <line id="c-axis-progress" x1="500" y1="42" x2="500" y2="42"
          stroke="#A9A99F" stroke-width="5" stroke-linecap="round" opacity="0"/>
    <!-- Thick spine stroke — grows top→bottom during "7 Jahre" sections as progress indicator -->
    <line id="spine-thick" x1="500" y1="42" x2="500" y2="42"
          stroke="#D63335" stroke-width="3" stroke-linecap="round" opacity="0"/>
    <rect id="spine-hit" x="486" y="42" width="28" height="468" fill="transparent"/>
  </svg>

  <!-- Scroll spacer sections injected here by the engine -->
  <div id="scroller"></div>

  <!-- Scene text overlays injected here by the engine -->
  <div id="overlays"></div>
`;
